//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_site
    {
        public string S_Id { get; set; }
        public string Station_Id { get; set; }
        public string Station_Name { get; set; }
        public string Route_Name { get; set; }
        public string Station_Ip { get; set; }
        public string Station_Port { get; set; }
        public string Station_Longitude { get; set; }
        public string Station_Latitude { get; set; }
        public Nullable<int> Del_State { get; set; }
        public string company { get; set; }
        public string province_station_name { get; set; }
        public string mask { get; set; }
        public string gateway { get; set; }
        public Nullable<int> lanes { get; set; }
        public string province_station_stake_mark { get; set; }
        public string System_Location_stake_mark { get; set; }
        public string Completion_date { get; set; }
        public string station_info { get; set; }
        public Nullable<int> link { get; set; }
        public Nullable<int> ping_state { get; set; }
        public Nullable<int> received_state { get; set; }
        public string province_station { get; set; }
    }
}
