//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_vehicle_msg
    {
        public string id_local { get; set; }
        public string Id { get; set; }
        public string Station_Id { get; set; }
        public System.DateTime Evt_Time { get; set; }
        public Nullable<System.DateTime> Msg_Time { get; set; }
        public Nullable<sbyte> Lane_No { get; set; }
        public string Plate { get; set; }
        public Nullable<sbyte> Plate_Color { get; set; }
        public Nullable<sbyte> Class_Index { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<sbyte> Direction { get; set; }
        public Nullable<sbyte> Axles_Count { get; set; }
        public Nullable<int> Total_Weight { get; set; }
        public Nullable<int> Axle1 { get; set; }
        public Nullable<int> Axle2 { get; set; }
        public Nullable<int> Axle3 { get; set; }
        public Nullable<int> Axle4 { get; set; }
        public Nullable<int> Axle5 { get; set; }
        public Nullable<int> Axle6 { get; set; }
        public Nullable<int> Axle7 { get; set; }
        public Nullable<int> Axle8 { get; set; }
        public Nullable<int> Axle9 { get; set; }
        public Nullable<int> Axle10 { get; set; }
        public Nullable<int> Axle_space1 { get; set; }
        public Nullable<int> Axle_space2 { get; set; }
        public Nullable<int> Axle_space3 { get; set; }
        public Nullable<int> Axle_space4 { get; set; }
        public Nullable<int> Axle_space5 { get; set; }
        public Nullable<int> Axle_space6 { get; set; }
        public Nullable<int> Axle_space7 { get; set; }
        public Nullable<int> Axle_space8 { get; set; }
        public Nullable<int> Axle_space9 { get; set; }
        public Nullable<sbyte> Is_Straddle { get; set; }
        public Nullable<int> Temperature { get; set; }
        public Nullable<int> Over_Weight { get; set; }
        public Nullable<double> Over_Weight_Ratio { get; set; }
        public string WIM_Id { get; set; }
        public string LPR_id { get; set; }
        public string Station_IP { get; set; }
        public Nullable<int> ValidityCode { get; set; }
        public Nullable<int> Wheelbase { get; set; }
        public Nullable<int> Gap { get; set; }
        public Nullable<int> TimeGap { get; set; }
        public Nullable<int> Headway { get; set; }
    }
}
